@startuml

actor Client as cli

folder "Object Storage" as keys {
  folder "Client #1" as c1k {
    frame "Private Key"   as pvk
    frame "Public Key"    as pbk

  }
}

folder "Object Storage" as creds {
  folder "Client #1" as c1c {
    frame "Client Secret" as cls

  }
}

frame "Authorization Server" {
  interface Server        as srvifc
  interface Authenticator as autifc
  interface Issuer        as issifc
  interface Repository    as keysifc
  interface Credentials   as credifc
  interface Usecase       as ucifc

  component Main as main

  component Server         as srvimpl
  component Authenticator  as autimpl
  component Issuer         as issimpl
  component Usecase        as ucimpl

  component "Keys\nRepository"        as keysimpl
  component "Credentials\nRepository" as credimpl

  srvimpl - srvifc
  ucimpl  - ucifc
  autimpl  - autifc
  issimpl  - issifc
  keysimpl - keysifc
  credimpl - credifc

  cli     -left-> main
  main    --> srvifc
  srvimpl --> ucifc
  
  ucimpl -up-> autifc
  ucimpl -left-> issifc
}

issimpl --> keysifc
autimpl -up-> credifc

keysimpl --> pvk
keysimpl --> pbk
credimpl  -up-> cls

@enduml