name: Golang

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19', '1.20' ]

    name: running in golang ${{ matrix.go }}
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup golang ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: run tests
      run: make test
